### ISSUE TITLE
支持大佬！！

### ISSUE THREAD

**Issue by ShanLangDang** [whc2001/ILCE7M3ExternalGps#2]

**Comment by whc2001** [comment]
虽然但是这个玩意已经坑了😂之前做了个原型但是逻辑太麻烦也懒得优化了，不过逆向出来的的数据包格式已经有了不知道有没有人愿意做（

**Comment by ShanLangDang** [comment]
最近全网搜索，寻找索尼A7M3\4相机的外挂GPS模块，只搜到佳能和尼康的，索尼这边您也是知道的只有APP同步，所以一直想找一个索尼能用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whc2001/ILCE7M3ExternalGps"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whc2001/ILCE7M3ExternalGps] 支持大佬！！ (Issue #2)





 
虽然但是这个玩意已经坑了😂之前做了个原型但是逻辑太麻烦也懒得优化了，不过逆向出来的的数据包格式已经有了不知道有没有人愿意做（

**Comment by whc2001** [comment]
确实，主要是索尼这个app在我之前那个手机上非常不稳定，只要切后台就不同步了，禁用节电模式之类的都不行，就想着干脆自己做个纯硬件的算了。不过我技术还不太够，得有大佬做出来成品😂之前那个原型倒是差不多能用但是实在是太简单了，代码太难看了所以一直没发
